apiVersion: v1
kind: Service
metadata:
  namespace: hung-argocd
  name: {{ .Release.Name }}
spec:
  type: NodePort
  selector: {{ include "common.labels" . | nindent 4 }}
  ports:
  - port: {{ .Values.port}}
    targetPort: {{ .Values.port}}
    nodePort: {{ .Values.nodePort}}
